name: Docker use in a Steps
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:  ## this container will be first created before running all the steps in it.
      image: node:20.3-alpine3.17 ## Coming from a public repo no need to authentication
      # credentials:
      #   username:
      #   password:
      env:
        API_URL: some-url.com
      ports:
        - 80
      # volumes:
      #   - vol_name:/path/in/container
      #   - /path/to/container
      #   - /path/in/host:/path/in/container
      # options: --cpus 1
    steps: ## This steps will run inside the container
     - name: Log Node & OS Versions
       run: |
        node -v
        cat /etc/os-release
     - name: Log Env
       run: echo $API_URL     
     - name: Container in a Step
       uses: docker://node:18.16-alpine3.17
       with:
        entrypoint: /usr/local/bin/node
        args: -p 2+3
     - name: Log node version
       uses: docker://node:18.16-alpine3.17
       with:
        args: -v

## Note: The containers running in steps level are not running inside the container at the job level. They are running as siblings
## so the share the same network and volumes, and ...