name: MAtrix
on: [push]

jobs:
  node-matrix:
    
    strategy:
      matrix:
        node-version: [14, 15, 16]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v