name: Staus Check Functions
on : [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Step 2
        id: step-2
        run: exit 1
      - name: Runs on Failure
        if: failure() && steps.step-2.conclusion == 'failure' ## run only if the step 2 is fail
        run: echo 'Step 2 has failed'
      - name: Runs on Success
        # This is not needed because (success) is the DEFAULT BEHAVIOUR
        if: success()
        run: echo 'Runs on Success'
      - name: Always Runs
        if: always() # It's the same thing like 'if: success() || failure()''
        run: echo 'Always Runs'
      - name: Runs when Cancelled
        if: cancelled()
        run: echo 'Runs on Cancelled'
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'Job 2'
