name: Timeout and Continue on Error
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    timeout-minutes: 1 ## Mark the job as failed/canceled if it takes more than 1 minute to finish
    steps:
      - name: Step 1
        run: sleep 90
        # timeout-minutes: 1 ## Mark the step as fail if it takes more than 1 minute to finish
      - name: Step 2
        id: step-2
        continue-on-error: true ## Even if there is an error, continue without making fail the job
        run: exit 1
      - name: Runs on step 2 Failure
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo 'Step 2 has failed'
      - name: Runs on Failure
        if: failure()
        run: echo 'Failure'
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'Job 2'